

cards:
  message: "Welcome to AbcBank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@AbcBank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721