server:
  port: 8071
spring:
  application:
    name: "ConfigServer"
  profiles:
    active: native
  cloud:
    config:
      server:
        search-locations: "classpath:/config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "KJHGR456789098765HNMEWREWO9876"




